// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/rates/supported-currencies": {
            "get": {
                "description": "Retrieve all supported currency codes for FX requests",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rates"
                ],
                "summary": "List supported currencies",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.GetSupportedCodesResponse"
                        }
                    }
                }
            }
        },
        "/rates/updates": {
            "post": {
                "description": "Schedule a rate update for a currency pair",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rates"
                ],
                "summary": "Schedule rate update",
                "parameters": [
                    {
                        "description": "ApplyUpdates parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.ScheduleUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/handler.ScheduleUpdateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/rates/updates/{id}": {
            "get": {
                "description": "Get the applied rate for a scheduled update ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rates"
                ],
                "summary": "Get rate by update ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Update ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "rate update applied",
                        "schema": {
                            "$ref": "#/definitions/handler.GetByUpdateIDApplied"
                        }
                    },
                    "202": {
                        "description": "rate update pending",
                        "schema": {
                            "$ref": "#/definitions/handler.GetByUpdateIDPending"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/rates/{base}/{quote}": {
            "get": {
                "description": "Get the latest applied FX rate by base/quote codes",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rates"
                ],
                "summary": "Get latest rate by codes",
                "parameters": [
                    {
                        "type": "string",
                        "example": "USD",
                        "description": "Base currency code",
                        "name": "base",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "EUR",
                        "description": "Quote currency code",
                        "name": "quote",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.GetByCodesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.RateUpdateStatus": {
            "type": "string",
            "enum": [
                "pending",
                "applied"
            ],
            "x-enum-varnames": [
                "StatusPending",
                "StatusApplied"
            ]
        },
        "handler.GetByCodesResponse": {
            "type": "object",
            "properties": {
                "base": {
                    "type": "string",
                    "example": "USD"
                },
                "quote": {
                    "type": "string",
                    "example": "EUR"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2025-01-02T15:04:05Z"
                },
                "value": {
                    "type": "number",
                    "example": 0.9231
                }
            }
        },
        "handler.GetByUpdateIDApplied": {
            "type": "object",
            "properties": {
                "base": {
                    "type": "string",
                    "example": "USD"
                },
                "quote": {
                    "type": "string",
                    "example": "EUR"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.RateUpdateStatus"
                        }
                    ],
                    "example": "applied"
                },
                "update_id": {
                    "type": "string",
                    "example": "77b5d9f5-0569-47e3-aee2-f659d59fbd97"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2025-01-02T15:04:05Z"
                },
                "value": {
                    "type": "number",
                    "example": 0.9231
                }
            }
        },
        "handler.GetByUpdateIDPending": {
            "type": "object",
            "properties": {
                "base": {
                    "type": "string",
                    "example": "USD"
                },
                "quote": {
                    "type": "string",
                    "example": "EUR"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.RateUpdateStatus"
                        }
                    ],
                    "example": "pending"
                },
                "update_id": {
                    "type": "string",
                    "example": "77b5d9f5-0569-47e3-aee2-f659d59fbd97"
                }
            }
        },
        "handler.GetSupportedCodesResponse": {
            "type": "object",
            "properties": {
                "codes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "USD",
                        "EUR",
                        "JPY"
                    ]
                }
            }
        },
        "handler.ScheduleUpdateRequest": {
            "type": "object",
            "properties": {
                "base": {
                    "type": "string",
                    "example": "USD"
                },
                "quote": {
                    "type": "string",
                    "example": "EUR"
                }
            }
        },
        "handler.ScheduleUpdateResponse": {
            "type": "object",
            "properties": {
                "update_id": {
                    "type": "string",
                    "example": "77b5d9f5-0569-47e3-aee2-f659d59fbd97"
                }
            }
        },
        "handler.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "something bad happened"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "FX Rates API",
	Description:      "API for scheduling and retrieving foreign exchange rates",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
